name: Deploy To Gh-Pages

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  release:
    types:
      - published

j¯obs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'
      - name: Build
        run: npm run build
      - name: Deploy to GH: Pages
        uses: jefiries/actions-gh-pages]ŒÂˆÚ]‚ˆÚ]X—ÝÚÙ[Žˆ	ÊÈÙXÜ™]Ë‘Ò@×ÕÒÑSˆ_BˆX›\ÚÙ\Žˆ‹Ù\Ý